"""
Django settings for your TOM project.

Originally generated by 'django-admin startproject' using Django 5.2.16.
Generated by ./manage.py tom_setup on July 29, 2026, 6:43 a.m.

For more information on this file, see
https://docs.djangoproject.com/en/stable/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/stable/ref/settings/
and
https://tom-toolkit.readthedocs.io/en/stable/common/customsettings.html
"""
import logging.config
import os
import tempfile
from tom_common.default_settings import *


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/stable/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("TOM_SECRET_KEY", "development-only-not-for-production")

# Old SECRET_KEY values to keep accepting during a graceful rotation. When
# you rotate SECRET_KEY, move the previous value into this list, restart,
# then run `python manage.py rotate_encryption_key` to re-encrypt stored
# data under the new key — after which you can remove the entry from this
# list. Leave it as [] until you rotate. See https://tom-toolkit.readthedocs.io/en/stable/deployment/encryption.html.
SECRET_KEY_FALLBACKS = []

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('TOM_DEBUG', '') == '1'

ALLOWED_HOSTS = os.environ.get('TOM_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

SNCLOCK_FRONTEND_DIST = os.environ.get('SNCLOCK_FRONTEND_DIST', os.path.join(BASE_DIR, '..', 'frontend', 'dist'))
TELESCOPE_SNAPSHOT_PATH = os.environ.get('TELESCOPE_SNAPSHOT_PATH', '')
TELESCOPE_SNAPSHOT_SYNTHETIC = os.environ.get('TELESCOPE_SNAPSHOT_SYNTHETIC', '') == '1'


# Application definition

TOM_NAME = 'tom_snclock'

# Use built-in css theme to change the look of your TOM. (Valid themes = [Dark,])
# CSS_THEME = 'Dark'

INSTALLED_APPS = TOMTOOKIT_INSTALLED_APPS + [
    'custom_code',
    'telescope_ops',
]

# Private local_settings supplies named proposal profiles and env-var references,
# never browser-provided endpoints or credentials. Off by default.
TELESCOPE_PROFILES = {}
TELESCOPE_OPERATIONS_ENABLED = False
TELESCOPE_REPORT_SYNC = {}

SITE_ID = 1

MIDDLEWARE = TOMTOOKIT_MIDDLEWARE + [
]

ROOT_URLCONF = 'tom_snclock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap5'

WSGI_APPLICATION = 'tom_snclock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '_static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'data')
MEDIA_URL = '/data/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO'
        }
    }
}

# Caching
# https://docs.djangoproject.com/en/4.2/topics/cache/#filesystem-caching

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(tempfile.gettempdir(), 'snclock-tom-cache')
    }
}

TASKS = {
    "default": {
        # "BACKEND": "django_tasks.backends.database.DatabaseBackend"
        "BACKEND": "django_tasks.backends.immediate.ImmediateBackend"
    }
}

# TOM Specific configuration
TARGET_TYPE = 'SIDEREAL'

# Set to the full path of a custom target model to extend the BaseTarget Model with custom fields.
# TARGET_MODEL_CLASS = 'custom_code.models.UserDefinedTarget'

# Define MATCH_MANAGERS here. This is a dictionary that contains a dotted module path to the desired match manager
# for a given model.
# For example:
# MATCH_MANAGERS = {
#    "Target": "custom_code.match_managers.CustomTargetMatchManager"
# }
MATCH_MANAGERS = {}

FACILITIES = {
    'LCO': {
        'portal_url': 'https://observe.lco.global',
        'api_key': '',
    },
    'GEM': {
        'portal_url': {
            'GS': 'https://139.229.34.15:8443',
            'GN': 'https://128.171.88.221:8443',
        },
        'api_key': {
            'GS': '',
            'GN': '',
        },
        'user_email': '',
        'programs': {
            'GS-YYYYS-T-NNN': {
                'MM': 'Std: Some descriptive text',
                'NN': 'Rap: Some descriptive text'
            },
            'GN-YYYYS-T-NNN': {
                'QQ': 'Std: Some descriptive text',
                'PP': 'Rap: Some descriptive text',
            },
        },
    },
}

# Define the valid data product types for your TOM.
# This is a dictionary of tuples to be used as ChoiceField options, with the first element being the type and the
# second being the display name.
# Be careful when removing items, as previously valid types will no
# longer be valid, and may cause issues unless the offending records are modified.
DATA_PRODUCT_TYPES = {
    'photometry': ('photometry', 'Photometry'),
    'fits_file': ('fits_file', 'FITS File'),
    'spectroscopy': ('spectroscopy', 'Spectroscopy'),
    'image_file': ('image_file', 'Image File')
}

DATA_PROCESSORS = {
    'photometry': 'tom_dataproducts.processors.photometry_processor.PhotometryProcessor',
    'spectroscopy': 'tom_dataproducts.processors.spectroscopy_processor.SpectroscopyProcessor',
}

TOM_FACILITY_CLASSES = [
    'tom_observations.facilities.lco_redirect.LCORedirectFacility',
    'tom_observations.facilities.gemini.GEMFacility',
]

# You can add science-specific parameters to targets in your TOM.  The best way to do this is
# to extend the Target model, or you can define extra target fields here.
# Field types can be any of "number", "string", "boolean" or "datetime"
# See https://tom-toolkit.readthedocs.io/en/stable/targets/target_fields.html for documentation on
# this feature
# For example:
# EXTRA_FIELDS = [
#     {'name': 'redshift', 'type': 'number'},
#     {'name': 'discoverer', 'type': 'string'},
#     {'name': 'eligible', 'type': 'boolean'},
#     {'name': 'discovery_date', 'type': 'datetime'}
# ]
EXTRA_FIELDS = []

# Map model labels to dotted paths of custom general search functions for HTMX tables.
# This allows overriding the default general search method without subclassing.
# See https://tom-toolkit.readthedocs.io/en/stable/customization/htmx_tables.html.
# Example:
# GENERAL_SEARCH_FUNCTIONS = {
#     'tom_targets.Target': 'custom_code.search.my_target_search',
# }
GENERAL_SEARCH_FUNCTIONS = {}

# This list can be used to add custom target parameters to the output from the target selection tool
SELECTION_EXTRA_FIELDS = []

# Authentication strategy can either be LOCKED (required login for all views, bypassed with OPEN_URLS)
# or READ_ONLY (read only access to views)
AUTH_STRATEGY = 'READ_ONLY'

# Row-level data permissions restrict users from viewing certain objects unless they are a member of the group to which
# the object belongs. Setting this value to True will allow all `ObservationRecord`, `DataProduct`, and `ReducedDatum`
# objects to be seen by everyone. Setting it to False will allow users to specify which groups can access
# `ObservationRecord`, `DataProduct`, and `ReducedDatum` objects.
TARGET_PERMISSIONS_ONLY = True

# Default permission for newly created targets. Values can be 'PRIVATE', 'PUBLIC', or 'OPEN'
TARGET_DEFAULT_PERMISSION = 'PRIVATE'

# Display these columns in the target list table. Values can be attributes or properties on
# the Target model, tags or extra fields. The fields `observations` and `saved_data` are
# special cases with custom implementation.
TARGET_LIST_COLUMNS = [
    "name", "type", "observations", "saved_data"
]

# URLs that should be allowed access even with AUTH_STRATEGY = LOCKED. Can use wildcards.
# for example: OPEN_URLS = ['/', '/about', '/accounts/reset/*/']
OPEN_URLS = []

HOOKS = {
    'target_post_save': 'tom_common.hooks.target_post_save',
    'observation_change_state': 'tom_common.hooks.observation_change_state',
    'data_product_post_upload': 'tom_dataproducts.hooks.data_product_post_upload',
    'data_product_post_save': 'tom_dataproducts.hooks.data_product_post_save',
    'multiple_data_products_post_save': 'tom_dataproducts.hooks.multiple_data_products_post_save',
}

AUTO_THUMBNAILS = False

THUMBNAIL_MAX_SIZE = (0, 0)

THUMBNAIL_DEFAULT_SIZE = (200, 200)

HINTS_ENABLED = False
HINT_LEVEL = 20

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # for API token authentication
        'rest_framework.authentication.SessionAuthentication',  # for logged-in browsers (cookie + CSRF protection)
        'rest_framework.authentication.BasicAuthentication',  # for username/password
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}

# Default Plotly theme setting, can set to any valid theme:
# 'plotly', 'plotly_white', 'plotly_dark', 'ggplot2', 'seaborn', 'simple_white', 'none'
PLOTLY_THEME = 'plotly_white'

STDWEB_API_URL = os.environ.get(
    "STDWEB_API_URL",
    "http://127.0.0.1:8021/api/",
)
STDWEB_PUBLIC_URL = os.environ.get(
    "STDWEB_PUBLIC_URL",
    "https://tom.snclock.com/reduce",
)
STDWEB_API_TOKEN = os.environ.get("STDWEB_API_TOKEN", "")

# Setting for displaying pagination information (e.g., "(0-0 of 0)").
# Set this to False if you have a particularly large DB and paginated views are slow.
SHOW_PAGINATION_INFO = True

try:
    from local_settings import * # noqa
except ImportError:
    pass
