# Generated by Django 5.2.16 on 2026-09-13 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0030_alter_basetarget_slope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=100)),
                ('specification', models.JSONField()),
                ('payload', models.JSONField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('config_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(null=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('request_ids', models.JSONField(default=list)),
                ('observation_state', models.CharField(default='unknown', max_length=80)),
                ('checked_at', models.DateTimeField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tom_targets.basetarget')),
            ],
            options={
                'permissions': [('approve_plan', 'Approve exact telescope payloads')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='telescope_ops.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=20)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='telescope_ops.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('action__in', ['submit', 'cancel'])), fields=('plan', 'action'), name='one_facility_write_per_plan_action')],
            },
        ),
    ]
