# Generated by Django 5.2.16 on 2026-09-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescope_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='registration_payload',
            field=models.JSONField(default=dict),
        ),
    ]
